modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"

description = '''
${mod_description}

Возможности:
• Отслеживание сообщений античита в реальном времени
• Интерактивные кнопки в чате для быстрых команд
• Настраиваемый HUD с информацией о нарушениях
• Система логирования и архивации
• История чата с фильтрацией
• Горячие клавиши для управления
• Звуковые уведомления
• Полная настройка через конфиг

Горячие клавиши:
F8 - переключить HUD
F9 - открыть историю чата
F10 - очистить записи

Команды кнопок:
• Проверить - /freezing [игрок]
• Спек - /matrix spectate [игрок]
'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"